apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: {{ timestamp }}
  name: {{ cluster_name }}
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{ s3_bucket }}/{{ cluster_name }}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: {{ master_instance_0 }}
      name: a-1
      encryptedVolume: true
    enableEtcdTLS: true
    name: main
    version: 3.3.1
  - etcdMembers:
    - instanceGroup: {{ master_instance_0 }}
      name: a-1
      encryptedVolume: true
    enableEtcdTLS: true
    name: events
    version: 3.3.1
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: {{ version }}
  masterPublicName: api.{{ cluster_name }}
  networkID: {{ vpc_id }}
  networkCIDR: {{ vpc_cidr }}
  networking:
    calico:
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  # Public subnets
  - name: {{ public_subnet_0_name }}
    cidr: {{ public_subnet_0_cidr }}
    type: Utility
    zone: {{ public_subnet_0_az }}
    #id: {{ public_subnet_0_id }}

  # Nat subnets
  - name: {{ nat_subnet_0_name }}
    cidr: {{ nat_subnet_0_cidr }}
    type: nodes
    zone: {{ nat_subnet_0_az }}
    egress: {{ natgateway_0 }}
    #id: {{ nat_subnet_0_id }}

  topology:
    bastion:
      bastionPublicName: bastion.{{ cluster_name }}
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: {{ timestamp }}
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: {{ master_instance_0 }}
spec:
  image: {{ image }}
  machineType: m4.xlarge
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{ nat_subnet_0_name }}
  nodeLabels:
    nodeType: master
  cloudLabels:
    cluster: {{ cluster_name }}
    nodeType: master

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: {{ timestamp }}
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: nodes-instance
spec:
  image: {{ image }}
  machineType: m4.xlarge
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 6
  minSize: 3
  role: Node
  subnets:
  - {{ nat_subnet_0_name }}
  nodeLabels:
    nodeType: private
  cloudLabels:
    cluster: {{ cluster_name }}
    nodeType: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: {{ timestamp }}
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: bastion
spec:
  image: {{ image }}
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - {{ public_subnet_0_name }}
  cloudLabels:
    cluster: {{ cluster_name }}
    nodeType: bastion
