---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ cluster_name }}
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{ s3_bucket }}/{{ cluster_name }}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: {{ master_instance_0 }}
      name: m1
      encryptedVolume: true
    - instanceGroup: {{ master_instance_1 }}
      name: m2
      encryptedVolume: true
    - instanceGroup: {{ master_instance_2 }}
      name: m3
      encryptedVolume: true
    name: main
  - etcdMembers:
    - instanceGroup: {{ master_instance_0 }}
      name: m1
      encryptedVolume: true
    - instanceGroup: {{ master_instance_1 }}
      name: m2
      encryptedVolume: true
    - instanceGroup: {{ master_instance_2 }}
      name: m3
      encryptedVolume: true
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.{{ cluster_name }}
  networkID: {{ vpc_id}}
  networkCIDR: {{ vpc_cidr }}
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  subnets:
    ### Subnets for LB/Bastion (Utility)
    - name: {{ public_subnet_0_name }}
      cidr: {{ public_subnet_0_cidr }}
      type: Utility
      zone: {{ public_subnet_0_az }}
      id: {{ public_subnet_0_id }}
    - name: {{ public_subnet_1_name }}
      cidr: {{ public_subnet_1_cidr }}
      type: Utility
      zone: {{ public_subnet_1_az }}
      id: {{ public_subnet_1_id }}
    - name: {{ public_subnet_2_name }}
      cidr: {{ public_subnet_2_cidr }}
      type: Utility
      zone: {{ public_subnet_2_az }}
      id: {{ public_subnet_2_id }}

    ### Subnets for Private nodes & masters
    - name: {{ nat_subnet_0_name }}
      cidr: {{ nat_subnet_0_cidr }}
      type: Private
      zone: {{ nat_subnet_0_az }}
      egress: {{ natgateway_0 }}
      id: {{ nat_subnet_0_id }}
    - name: {{ nat_subnet_1_name }}
      cidr: {{ nat_subnet_1_cidr }}
      type: Private
      zone: {{ nat_subnet_1_az }}
      egress: {{ natgateway_1 }}
      id: {{ nat_subnet_1_id }}
    - name: {{ nat_subnet_2_name }}
      cidr: {{ nat_subnet_2_cidr }}
      type: Private
      zone: {{ nat_subnet_2_az }}
      egress: {{ natgateway_2 }}
      id: {{ nat_subnet_2_id }}
  topology:
    bastion:
      bastionPublicName: bastion.{{ cluster_name }}
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: {{ master_instance_0 }}
spec:
  image: {{ image }}
  machineType: {{ masters }}
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: {{ master_instance_0 }}
  cloudLabels:
    feedyard: "True"
  role: Master
  subnets:
    - {{ nat_subnet_0_name }}

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: {{ master_instance_1 }}
spec:
  image: {{ image }}
  machineType: {{ masters }}
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: {{ master_instance_1 }}
  cloudLabels:
    feedyard: "True"
  role: Master
  subnets:
    - {{ nat_subnet_1_name }}

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: {{ master_instance_2 }}
spec:
  image: {{ image }}
  machineType: {{ masters }}
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: {{ master_instance_2 }}
  cloudLabels:
    feedyard: "True"
  role: Master
  subnets:
    - {{ nat_subnet_2_name }}

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: nodes
spec:
  image: {{ image }}
  machineType: {{ nodes }}
  rootVolumeSize: 40
  rootVolumeType: gp2
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  cloudLabels:
    feedyard: "True"
  role: Node
  subnets:
    - {{ nat_subnet_0_name }}
    - {{ nat_subnet_1_name }}
    - {{ nat_subnet_2_name }}

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ cluster_name }}
  name: bastion
spec:
  image: {{ image }}
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
    - {{ nat_subnet_0_name }}
  cloudLabels:
    feedyard: "True"
    nodeType: bastion
