version: 2

defaults: &defaults
  working_directory: ~/baseline-platform-aws-k8
  environment:
    BASH_ENV: local.env
    K8_VERSION: 1.8.4
    AMI: "kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14"
  docker:
    - image: quay.io/feedyard/circleci-infra-agent

jobs:

  configure-sandbox-cluster:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: setup aws profile
          command: bash setup_profile.sh $feedyard_svc_user_key $feedyard_svc_user_secret
      - run:
          name: assume kops role
          command: source setup_assume_role.sh $sandbox_kops_role
      - run:
          name: setup terraform state file location
          command: bash setup_backend.sh sandbox
      - run:
          name: initialize the terraform state backend
          command: invoke init
      - run:
          name: output terraform state information
          command: invoke output
      - run:
          name: render kops config temmplate
          command: |
            python3 render_kops_template.py feedyard sandbox $K8_VERSION $AMI
            cat sandbox_cluster.yml
#      - run:
#          name: create/update kubernetes cluser
#          command: bash setup_kubernetes.sh feedyard sandbox feedyard.io

  validate-sandbox-cluster:
      <<: *defaults

      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: confirm Docker
            command: docker info
        - run:
            name: decrypt secrets
            command: invoke dec
        - run:
            name: setup aws profile
            command: bash setup_profile.sh $feedyard_svc_user_key $feedyard_svc_user_secret
        - run:
            name: assume nonprod role
            command: source setup_assume_role.sh $sandbox_kops_role
        - run:
            name: validate cluster
            command: validate_cluster.sh feedyard sandbox feedyard.io


workflows:
  version: 2
  baseline-platform-aws-k8-pipeline:
    jobs:
      - configure-sandbox-cluster
      - validate-sandbox-cluster:
          type: approval
          requires:
            - configure-sandbox-cluster
